version: 1.0.0.{build}

configuration:
 - Release

platform:
 - Win32
 - x64

image:
 - Visual Studio 2019

install:
 - cmd: 'if "%platform%"=="Win32" vcpkg install libpng:x86-windows zlib:x86-windows'
 - cmd: 'if "%platform%"=="x64" vcpkg install libpng:x64-windows zlib:x64-windows'
 - cmd: 'cd c:\tools\vcpkg && vcpkg integrate install'

cache:
 - c:\tools\vcpkg\installed\

build:
 project: vs2010.sln
 verbosity: minimal
 parallel: true

before_build :
 - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe" /upgrade vs2010.sln'
 - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe" /upgrade vs2010.vcxproj'

artifacts:
 - path: bin/*/sm2lbpp.exe
