name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: libpng-dev
          version: 1.0
    - name: Build
      run: make all
